CREATE TABLE USUARIO (
COD INTEGER NOT NULL,
NOME varchar(50) NOT NULL,
EMAIL varchar(50) NOT NULL,
SENHA varchar(6) NOT NULL,
TELEFONE varchar(15) NOT NULL,
ISADMIN BOOLEAN NOT NULL,
LOGRADOURO varchar(50) NOT NULL,
NUMEROEND INTEGER NOT NULL,
BAIRRO varchar(30) NOT NULL,
CIDADE varchar(50) NOT NULL,
UF CHAR(2) NOT NULL,
EMPRESA INTEGER NOT NULL,
ATIVO bool NOT NULL,
TOKEN varchar(30),
PRIMARY KEY (COD) 
)
;
CREATE TABLE EMPRESA (
COD INTEGER NOT NULL,
NOME varchar(50) NOT NULL,
PRIMARY KEY (COD) 
)
;
CREATE TABLE TIPOITEM (
COD INTEGER NOT NULL,
DESCRICAO varchar(50) NOT NULL,
PRIMARY KEY (COD) 
)
;
CREATE TABLE ITEM (
COD INTEGER NOT NULL,
DESCRICAO varchar(50) NOT NULL,
TIPOITEM INTEGER NOT NULL,
DATACADASTRO DATE NOT NULL,
MARCA varchar(50),
ATIVO BOOLEAN NOT NULL,
PRIMARY KEY (COD) 
)
;
CREATE TABLE RESERVA (
COD INTEGER NOT NULL,
DATAINICIO date NOT NULL,
DATAFIM date,
ATIVO BOOLEAN NOT NULL,
USUARIO INTEGER NOT NULL,
ITEM INTEGER NOT NULL,
EMPRESA INTEGER NOT NULL,
OBS varchar(255) NOT NULL,
STATUS INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY (COD) 
)
;
CREATE TABLE SALA (
COD INTEGER NOT NULL,
NOME varchar(50) NOT NULL,
DESCRICAO varchar(255) NOT NULL,
DISPONIVEL BOOLEAN NOT NULL,
PRIMARY KEY (COD) 
)
;
CREATE TABLE LOCALIZACAO (
ITEM INTEGER NOT NULL,
SALA INTEGER NOT NULL,
PRIMARY KEY (ITEM, SALA) 
)
;
CREATE TABLE RESERVASALA (
COD INTEGER NOT NULL,
SALA INTEGER NOT NULL,
DATAHORAINICIO TIMESTAMP(0) NOT NULL,
DATAHORAFIM TIMESTAMP(0) NOT NULL,
USUARIO INTEGER NOT NULL,
ATIVO BOOLEAN NOT NULL,
EMPRESA inteGER NOT NULL,
OBS varchar(255) NOT NULL,
PRIMARY KEY (COD) 
)
;
CREATE TABLE NOTIFICACAO (
COD INTEGER NOT NULL,
EMPRESA INTEGER NOT NULL,
EVENTO varchar(255) NOT NULL,
DADOS varchar(255) NOT NULL,
COMENTARIO varchar(255) NOT NULL,
DATANOTIF timestamp(0) NOT NULL,
PRIMARY KEY (COD) 
)
;
CREATE TABLE USUARIOPEND (
COD INTEGER NOT NULL,
NOME varchar(50) NOT NULL,
EMAIL varchar(50) NOT NULL,
SENHA varchar(6) NOT NULL,
TELEFONE varchar(15) NOT NULL,
LOGRADOURO varchar(50) NOT NULL,
NUMEROEND INTEGER NOT NULL,
BAIRRO varchar(30) NOT NULL,
CIDADE varchar(50) NOT NULL,
UF CHAR(2) NOT NULL,
EMPRESA INTEGER NOT NULL,
PRIMARY KEY (COD) 
)
;

ALTER TABLE USUARIO ADD CONSTRAINT EMPRESA_FK FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ITEM ADD CONSTRAINT TIPOITEM_FK FOREIGN KEY (TIPOITEM) REFERENCES TIPOITEM (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVA ADD CONSTRAINT ITEM_FK FOREIGN KEY (ITEM) REFERENCES ITEM (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVA ADD CONSTRAINT USER_FK FOREIGN KEY (USUARIO) REFERENCES USUARIO (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE LOCALIZACAO ADD CONSTRAINT FK_SALA FOREIGN KEY (SALA) REFERENCES SALA (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE LOCALIZACAO ADD CONSTRAINT FK_ITEM FOREIGN KEY (ITEM) REFERENCES ITEM (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVASALA ADD CONSTRAINT FK_SALA FOREIGN KEY (SALA) REFERENCES SALA (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVASALA ADD CONSTRAINT FK_USER FOREIGN KEY (USUARIO) REFERENCES USUARIO (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVA ADD CONSTRAINT EMPRESA_FK FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE NOTIFICACAO ADD CONSTRAINT FK_EMPRESA FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVASALA ADD CONSTRAINT FK_EMPRESA FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (COD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE USUARIOPEND ADD CONSTRAINT FK_EMP FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (COD) ON DELETE CASCADE ON UPDATE CASCADE;

